### PR TITLE
Remove unused code

### PR DESCRIPTION
**Pull request by swooboo**
This PR removes unused fields and unused lines of code.

### CODE REVIEW

**Comment by swooboo** [comment]
I don't get it, what's the problem? It compiles on my PC!

```
completed successfully | 1m 12s 422ms
-- | --
Run build | 1m 12s 45ms
Load build | 46ms
Configure build | 661ms
Calculate task graph | 1s 108ms
Run tasks | 1m 10s 222ms
null |  
The rule `-keep public class *extends java.lang.annotation.Annotation { |  
```

The `-keep public` warning appears on the master branch as well so it can't be it... @Mikhael-Danilov help please?

**Comment by swooboo** [comment]
Hmm now `codebeat` seems to be having issues - it's in "Pending" state for a long time now. Is this normal?

**Comment by Mikhael-Danilov** [comment]
Provided it is free account it can be normal, I will check it.
Did you sure about changes in ShadowCaster.java ?

**Comment by swooboo** [comment]
Here are my thoughts about this:

1. The only line from this year in it - https://github.com/NYRDS/pixel-dungeon-remix/blame/26057cc8cecc18bc3ea2296b7a8cb3ac1a76eff3/PixelDungeon/src/main/java/com/watabou/pixeldungeon/mechanics/ShadowCaster.java#L51
1. This means that it's an old file without ongoing work on it.
1. I removed the code that does literally nothing - unused variables, useless if-then conditions, unused fields.
1. I'm pretty confident in my changes but you're welcome to challenge specific points.

**Comment by Mikhael-Danilov** [comment]
On this branch first Sewers level looks like this:

screenshot_1529184989

(Yes no map visible at all)

**Comment by swooboo** [comment]
OK I'll review, sorry about that.

**Comment by swooboo** [comment]
Your guess was right, the last commit was the problem. I've removed it from the PR, let's wait until it is checked. Sorry again. I still don't understand why this happened, so I'll investigate further in the future?

**Comment by Mikhael-Danilov** [comment]
There is no unused code in ShadowCaster.java at time, and static analysis systems sometimes produces false positives. So every non-trivial hint from such systems require a careful review and a testing.
All others changes looks fine. Thanks!

**Comment by swooboo** [comment]
Well it's not only the static analysis, but also Android Studio that showed no code using the fields I removed, and the code I removed acted upon these fields only so I removed it too... Weird. I learned my lesson though, thanks.

**Pull request merged**
