### PR TITLE
Remove unused imports

### PR DESCRIPTION
**Pull request by swooboo**
This PR removes all unused imports from the project. Part of #44 , splitting up the big PR into smaller atomic chunks.

### CODE REVIEW

**Comment by swooboo** [comment]
I can't see the details for bitrise - what's the problem there?

**Comment by swooboo** [comment]
@Mikhael-Danilov can you give me read-only access to the bitrise project? It would help me see where the build fails.

**Comment by Mikhael-Danilov** [comment]
Invitation sent

**Comment by Mikhael-Danilov** [comment]
@swooboo Looks like there is issue with signing key availability for PRs.
I will sort out this soon.

**Comment by swooboo** [comment]
Thank you! I need more help now. It just says 'Failed', but I can't find any additional info / logs / error messages. Where is all of it? Do you know why it failed?

**Comment by swooboo** [comment]
When you sort this out, can I re-run bitrise for my PRs somehow? Or is it automatic?

**Comment by Mikhael-Danilov** [comment]
1) Now PR will build unsigned apk
2) You will be able to view logs 
3) re-run builds manually or by placing dummy commit on PR source branch

**Comment by Mikhael-Danilov** [comment]
No nothing wrong with it ( although some google related stuff will not work in such builds )

**Pull request merged**
