### PR TITLE
Remove unused code and close #43

### LINKED ISSUE #43: Unused code from Codacy
Codacy shows some unused code [here](https://app.codacy.com/app/NYRDS/pixel-dungeon-remix/issues?&filters=W3siaWQiOiJDYXRlZ29yeSIsInZhbHVlcyI6WyJVbnVzZWQgQ29kZSJdfV0=). I'll remove the code.

### PR DESCRIPTION
**Pull request by swooboo**
This PR resolves all the "Unused code" issues from Codacy report. ([link](https://app.codacy.com/app/NYRDS/pixel-dungeon-remix/issues?&filters=W3siaWQiOiJMYW5ndWFnZSIsInZhbHVlcyI6W251bGxdfSx7ImlkIjoiQ2F0ZWdvcnkiLCJ2YWx1ZXMiOlsiVW51c2VkIENvZGUiXX0seyJpZCI6IkxldmVsIiwidmFsdWVzIjpbbnVsbF19LHsiaWQiOiJQYXR0ZXJuIiwidmFsdWVzIjpbbnVsbF19LHsiaWQiOiJBdXRob3IiLCJ2YWx1ZXMiOltudWxsXX1d))

Note that last commit edits recent files and I am not entirely sure they should be changed. Refer to the discussion in #43 for more info.

### CODE REVIEW

**Comment by Mikhael-Danilov** [comment]
Thanks for your efforts but I cannot accept this PR - too many things mixed in.
1) unused imports - all ok ( likely some settings changed on AS updated, and they don't clears automatically any more
2) android/google/ - i prefer do not touch this
3) verifyDeveloperPayload(Purchase p) - not ok, I plan to implement proper checking sometime
4) unused classes - probably ok
5) excessive parameters - probably ok, but each case need review 

Please make more atomic PRs.

Thanks!

**Comment by swooboo** [comment]
Sure, good point. I'll reorganize and resubmit.

**Comment by Mikhael-Danilov** [comment]
Files from this path PixelDungeon/src/main/java/com/nyrds/android/google/util

**Comment by swooboo** [comment]
I've started dividing this into smaller PRs. Already submitted the imports one. Now working on all others. Can you help with excessive parameters? My question - if each case needs a review, how granular do you want me to be? One PR for each file?

**Comment by Mikhael-Danilov** [comment]
Great!
One PR per case ( probably this will affect multiple files )

**Pull request closed without merging**
